# fly.toml app configuration file generated for eco on 2024-09-27T13:01:23+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eco'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
